# Netlify yapılandırmaları - MehmetEndustriyelTakip
[build]
  publish = "dist"
  command = "chmod +x ./build.sh && ./build.sh"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"
  # Dashboard dosyası hatasını önlemek için ek çevre değişkenleri
  VITE_USE_DIRECT_IMPORTS = "true"
  VITE_DISABLE_PWA = "false"
  # SASS legacy API uyarılarını bastır
  SASS_BINARY_NAME = "linux-x64-93"
  # Uyarıları hata olarak değerlendirmeyi engelle
  CI_WARNINGS_AS_ERRORS = "false"

# Service Worker'ın doğru şekilde sunulmasını sağla
[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200
  force = true
  headers = { Content-Type = "application/javascript; charset=utf-8" }

# Manifest dosyasının doğru şekilde sunulmasını sağla
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = true
  headers = { Content-Type = "application/manifest+json; charset=utf-8" }

# Workbox dosyalarının doğru şekilde sunulmasını sağla
[[redirects]]
  from = "/workbox-*.js"
  to = "/workbox-:splat.js"
  status = 200
  force = true
  headers = { Content-Type = "application/javascript; charset=utf-8" }

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Son olarak tüm yolları index.html'e yönlendir (SPA yapısı için)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# HTTP güvenlik başlıkları
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; img-src 'self' data: https:; font-src 'self' data: https://cdn.jsdelivr.net https://cdnjs.cloudflare.com;"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache kontrolü
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service worker dosyaları için Cache-Control
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/manifest+json; charset=utf-8"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript; charset=utf-8"

# Gzip ve Brotli sıkıştırma aktif
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true